d1210/stu_project/home/urls.py
from django.urls import path,include
from . import views

app_name=''
urlpatterns = [
    path('',views.index,name='index')
    
]

d1210/stu_project/student/urls.py
from django.urls import path,include
from . import views

app_name='student'
urlpatterns = [
    path('list/',views.list,name='list'),
    path('write/',views.write,name='write'),
    path('view/<int:sno>/',views.view,name='view'),
    path('delete/',views.delete,name='delete'),
    
]

d1210/stu_project/stuproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('student/', include('student.urls')),
    path('stuscore/', include('stuscore.urls')),
    
    
]

d1210/stu_project/stuscore/urls.py
from django.urls import path,include
from . import views

app_name='student'
urlpatterns = [
    path('write/',views.write,name='write')
    
]

d1210/stu_project/student/models.py
# model db를 생성하는 페이지
from django.db import models


# 테이블을 생성하면 항상 id가 자동생성됨: AutoField
# 앱안에 테이블명으로 기입, student앱_Student
class Student(models.Model):
    sno= models.AutoField(primary_key=True)
    name= models.CharField(max_length=100)
    age= models.IntegerField(default=1)
    grade= models.IntegerField(default=1)
    gender= models.CharField(max_length=10)
    hobby= models.CharField(max_length=100,default='게임')
    
    
    def __str__(self):
        return f"{self.sno},{self.name},{self.age},{self.grade},{self.gender}"

d1210/stu_project/stuscore/models.py
from django.db import models

class Stuscore(models.Model):
    sno= models.AutoField(primary_key=True)
    name= models.CharField(max_length=100)
    kor= models.IntegerField(default=0)
    eng= models.IntegerField(default=0)
    math= models.IntegerField(default=0)
    total= models.IntegerField(default=0)
    avg= models.FloatField(default=0)
    
    
    def __str__(self):
        return f"{self.sno},{self.name},{self.total}"

d1210/stu_project/student/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from .models import Student


# 학생등록함수
def write(request):
    if request.method == 'GET':
        return render(request,'student/write.html')
    
    elif request.method == 'POST':
        
        # form 폼에서 넘어온 데이터처리
        name= request.POST.get("name")
        age= request.POST.get("age")
        grade= request.POST.get("grade")
        gender= request.POST.get("gender")
        hobby= request.POST.getlist("hobby")
        # hobbys= ",".join(hobby) # 리스트타입을 문자열타입으로 변환하는 방법
        # 리스트타입을 문자열항목에 저장하면 자동으로 형변환됨
        
        # 입력과 동시에 저장
        qs= Student(name=name,age=age,grade=grade,gender=gender,hobby=hobby)
        qs.save()
        
        return redirect(reverse('student:list'))
        # return redirect('/student/list/')
        
        # print("이름",request.POST.get("name"))
        # print("나이",request.POST.get("age"))
        # print("학년",request.POST.get("grade"))
        # print("성별",request.POST.get("gender"))
        # print("취미",request.POST.getlist("hobby"))
        
        
        

# 학생리스트함수
def list(request):
    qs= Student.objects.all().order_by('-sno')
    context= {"our_class":"SM유니버스 직무교육","stu_list":qs}
    return render(request,'student/list.html',context)

# 학생상세보기 함수 - RESTful: 링크자체에 데이터값만을 실어서 보내는 방법
                # GET: 링크에 변수를 설정해 변수에 데이터값을 넣어 데이터를 실어보내는 방법
def view(request,sno):
    
    # GET.get 방식을 많이써라  # 데이터가 없으면 NONE 
    
    # age= request.GET['age'] # 데이터 없으면 에러
    
    print("넘어온 데이터 sno: ",sno)
    qs= Student.objects.get(sno=sno)
    context={"stu":qs}
    return render(request,'student/view.html',context)

# 학생리스트함수
def delete(request):
    return render(request,'student/list.html')

d1210/stu_project/stuscore/views.py
from django.shortcuts import render

def write(request):
    return render(request,'stuscore/write.html')

d1210/stu_project/student/templates/student/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>학생리스트</title>
    <style>
        h2{text-align:center;}
        table{margin:0 auto;}
        table,tr,th{border: 1px solid black; border-collapse:collapse;}
        th,td{width:150px; height:40px; text-align:center;}
        #btn{width:800; height:50px; margin:30px auto; border:none;}
        .d01{width:200px; height:50px; text-align:center;
            border:1px solid black; margin:0 auto; line-height:50px;
            background:#eee;}
        a{text-decoration:none;}
    </style>
</head>
<body>
    <!--html 주석-->
    {%comment%}디장고 주석은 다음과 같습니다{%endcomment%}

    <h2>{{our_class}} 학생리스트</h2>
    <h2>{{stu_inf}}</h2>
    <table>
        <tr>
            <th>번호</th>
            <th>이름</th>
            <th>나이</th>
            <th>학년</th>
            <th>성별</th>
        </tr>
        {%if stu_list%}
            {%for s in stu_list%}
            <tr>
                <th>{{s.sno}}</th>
                <th>   
                    {%comment%}

                    폼 태그는 POST, 그외에는 모두 GET 방식이다   
                    GET 방식으로 링크에 데이터 보내는 방법은 아래와 같다

                    <a href='/student/{{s.sno}}/view'>{{s.name}}</a>
                    <a href='/student/view?age=20'>{{s.name}}</a>
                    
                    {%endcomment%}

                    <a href='{%url "student:view" s.sno %}'>{{s.name}}</a>
                </th>
                <th>{{s.age}}</th>
                <th>{{s.grade}}</th>
                <th>{{s.gender}}</th>
            </tr>
            {%endfor%}
        {%else%}
        <tr>
            <td colspan='5'>데이터가 존재하지않습니다</td>
        </tr>
        {%endif%}
    </table>
    <div id="btn">
        <div class="d01"><a href="/student/write">글쓰기</a></div>
    </div>
</body>
</html>

d1210/stu_project/student/templates/student/view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>학생상세보기</title>
    <style>
        h2{text-align:center;}
        table{margin:30px auto; text-align:center;}
        th{width:200px;}
        td{width:300px;}
        table,th,td{border:1px solid black; border-collapse:collapse;}
        #btn{width:800; height:50px; margin:30px auto; border:none;}
        .d01{width:200px; height:50px; text-align:center;
            border:1px solid black; margin:0 auto; line-height:50px;
            background:#eee;}
    </style>
</head>
<body>
    <h2>학생 상세보기</h2>
    <h2>{{stu}}</h2>
    <table>
        <tr>
            <th>번호</th>
            <td>{{stu.sno}}</td>
        </tr>
        <tr>
            <th>이름</th>
            <td>{{stu.name}}</td>
        </tr>
        <tr>
            <th>나이</th>
            <td>{{stu.age}}</td>
        </tr>
        <tr>
            <th>학년</th>
            <td>{{stu.grade}}</td>
        </tr>
        <tr>
            <th>성별</th>
            <td>{{stu.gender}}</td>
        </tr>
        <tr>
            <th>취미</th>
            <td>{{stu.hobby}}</td>
        </tr>
    </table>
    <div id="btn">
        <div class="d01"><a href="/student/list">리스트</a></div>
    </div>
</body>
</html>

d1210/stu_project/student/templates/student/write.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>학생등록</h2>
    <form action="{%url 'student:write'%}" method="post">
        {%csrf_token%}
        <label>이름</label>
        <input type="text" name="name"><br>
        <label>나이</label>
        <input type="text" name="age"><br>
        <label>학년</label>
        <input type="text" name="grade"><br>
        <label>성별</label><br>
        <label for="남자">남자</label>
        <input type="radio" name="gender" value="남자"><br>
        <label for="여자">여자</label>
        <input type="radio" name="gender" value="여자"><br>
        <label>취미</label><br>
        <label for="게임">게임</label>
        <input type="checkbox" name="hobby" value="게임"><br>
        <label for="골프">골프</label>
        <input type="checkbox" name="hobby" value="골프"><br>
        <label for="수영">수영</label>
        <input type="checkbox" name="hobby" value="수영"><br>
        <label for="조깅">조깅</label>
        <input type="checkbox" name="hobby" value="조깅"><br>
        <label for="다꾸">다꾸</label>
        <input type="checkbox" name="hobby" value="다꾸"><br>
        <input type="submit" value="학생등록"><br>
    </form>



    
    <ul>
        <li><a href="/">메인페이지로 이동</a></li>
    </ul>
</body>
</html>

d1210/stu_project/stuscore/templates/stuscore/write.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>학생성적등록</h2>
</body>
</html>